import fs from 'node:fs';
import path from 'node:path';
import { resolveInWorkspace, type ToolDef } from './common';
import { svgToPng } from './chart';

const cleanHex = (v: unknown, fallback: string): string => {
  const t = typeof v === 'string' ? v.trim() : '';
  if (/^#?[0-9a-fA-F]{6}$/.test(t)) return t.startsWith('#') ? t : `#${t}`;
  return fallback;
};

/** White or near-black, whichever reads on the accent (relative luminance). */
function readableOn(hex: string): string {
  const h = hex.replace('#', '');
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
  const lin = (c: number) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
  const L = 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
  return L > 0.45 ? '#0b0b0c' : '#ffffff';
}

/** A clean, full-bleed branded icon (accent field + centred monogram inside the maskable safe zone),
 *  so the SAME asset is valid for both "any" and "maskable" purposes. Deterministic — no image gen. */
function iconSvg(letter: string, bg: string, fg: string, size: number): string {
  const fontSize = Math.round(size * 0.46); // keeps the glyph inside the central 80% safe zone
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="${bg}"/>
  <text x="50%" y="50%" dy=".35em" text-anchor="middle" font-family="Inter, system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" font-weight="700" font-size="${fontSize}" fill="${fg}">${letter}</text>
</svg>`;
}

/** A robust, probe-safe service worker: network-first for navigations (updates always show, offline
 *  falls back to the shell), cache-first for same-origin static GETs, and PASS-THROUGH for non-GET +
 *  cross-origin (so APIs are never broken). Versioned cache, instant activation. */
const SERVICE_WORKER = `// Generated by ArksAI — a safe offline-capable service worker.
const CACHE = 'arksai-pwa-v1';
const SHELL = ['./', './index.html'];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL).catch(() => {})).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  // Never touch non-GET or cross-origin requests (APIs, analytics, fonts on a CDN).
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  // Navigations: network-first so a republish is seen immediately; offline → cached shell.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((r) => { const copy = r.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); return r; })
        .catch(() => caches.match(req).then((m) => m || caches.match('./index.html'))),
    );
    return;
  }
  // Static assets: cache-first, fill the cache on a miss.
  e.respondWith(
    caches.match(req).then((m) =>
      m ||
      fetch(req)
        .then((r) => { if (r && r.ok) { const copy = r.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); } return r; })
        .catch(() => m),
    ),
  );
});
`;

const REG_SCRIPT =
  `<script>if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){})});}</script>`;

/** Find the HTML entry to wire the PWA into, and the static root to drop assets in. A Vite/CRA app
 *  keeps a `public/` that the build copies to the output root → assets go there; a plain static site
 *  gets them next to its index.html. Returns null when there's no HTML to attach to. */
function locateApp(destAbs: string): { htmlFile: string; assetRoot: string } | null {
  const rootIndex = path.join(destAbs, 'index.html');
  if (fs.existsSync(rootIndex)) {
    const publicDir = path.join(destAbs, 'public');
    // Vite source index.html at root + a public/ → assets must live in public/ to reach the build output.
    const assetRoot = fs.existsSync(path.join(destAbs, 'vite.config.ts')) || fs.existsSync(path.join(destAbs, 'vite.config.js'))
      ? (fs.existsSync(publicDir) ? publicDir : (fs.mkdirSync(publicDir, { recursive: true }), publicDir))
      : destAbs;
    return { htmlFile: rootIndex, assetRoot };
  }
  // CRA-style public/index.html
  const pubIndex = path.join(destAbs, 'public', 'index.html');
  if (fs.existsSync(pubIndex)) return { htmlFile: pubIndex, assetRoot: path.join(destAbs, 'public') };
  // Any other top-level .html
  const html = fs.readdirSync(destAbs).find((f) => f.toLowerCase().endsWith('.html'));
  if (html) return { htmlFile: path.join(destAbs, html), assetRoot: destAbs };
  return null;
}

/** Inject the PWA <head> tags + the registration script into an HTML file (idempotent). */
function wireHtml(htmlFile: string, themeColor: string, hasPng: boolean): void {
  let html = fs.readFileSync(htmlFile, 'utf8');
  const headTags = [
    `<link rel="manifest" href="manifest.webmanifest">`,
    `<meta name="theme-color" content="${themeColor}">`,
    `<link rel="apple-touch-icon" href="icons/${hasPng ? 'icon-192.png' : 'icon.svg'}">`,
    !/name=["']viewport["']/.test(html) ? `<meta name="viewport" content="width=device-width, initial-scale=1">` : '',
  ].filter(Boolean);
  if (!html.includes('rel="manifest"')) {
    const headOpen = html.match(/<head[^>]*>/i);
    if (headOpen) html = html.replace(headOpen[0], `${headOpen[0]}\n    ${headTags.join('\n    ')}`);
    else html = `${headTags.join('\n')}\n${html}`; // no <head> — prepend (degenerate, but never lose the tags)
  }
  if (!html.includes("serviceWorker.register")) {
    if (/<\/body>/i.test(html)) html = html.replace(/<\/body>/i, `  ${REG_SCRIPT}\n</body>`);
    else html += `\n${REG_SCRIPT}\n`;
  }
  fs.writeFileSync(htmlFile, html);
}

/**
 * Turn the app in this workspace into an installable PWA — correct BY CONSTRUCTION, so it never sends
 * the verify gate into a fix loop: a valid manifest, a safe offline service worker, and real app
 * icons generated deterministically (SVG → PNG, never a missing icon file), all wired into the HTML.
 */
export const addPwaTool: ToolDef = {
  name: 'add_pwa',
  description:
    'Make the app in this workspace an INSTALLABLE PWA in one correct-by-construction step — use this ' +
    'instead of hand-writing a manifest, service worker, or icons (hand-rolled PWAs miss an icon file or ' +
    'ship a service worker that breaks the checks, which sends the build into a slow fix loop). It writes a ' +
    'valid manifest.webmanifest, a safe offline service worker (sw.js: network-first navigation so updates ' +
    'show, cache-first assets, pass-through for APIs), and REAL app icons generated deterministically ' +
    '(icons/icon.svg always, plus icon-192/512.png when possible — never a missing icon), then wires the ' +
    'manifest link, theme-color, apple-touch-icon and the service-worker registration into the app HTML. ' +
    'Call it AFTER the web app is built, when the user wants an installable / "add to home screen" / offline ' +
    'app. Works for a plain static site (writes beside index.html) and for a Vite/CRA app (writes into ' +
    'public/). Then publish_app as usual.',
  parameters: {
    type: 'object',
    properties: {
      name: { type: 'string', description: 'App name shown on the install prompt / home screen (e.g. "Onda Car Care").' },
      short_name: { type: 'string', description: 'Short name for the home-screen label (<= 12 chars ideal). Defaults from name.' },
      theme_color: { type: 'string', description: 'Theme/brand color hex (the status bar + icon background). Use the brand accent.' },
      background_color: { type: 'string', description: 'Splash background hex. Defaults to white.' },
      dest: { type: 'string', description: 'Workspace subfolder of the app (default the workspace root ".").' },
    },
  },
  modes: ['code'],
  summarize: (a) => `add PWA${a?.name ? ` "${a.name}"` : ''}`,
  async run(args, ctx) {
    const destRel = String(args.dest ?? '.').replace(/[^a-zA-Z0-9._/-]/g, '-') || '.';
    let destAbs: string;
    try {
      destAbs = resolveInWorkspace(ctx.repoDir, destRel);
    } catch (e: any) {
      return `Error: ${e?.message ?? e}`;
    }
    if (!fs.existsSync(destAbs)) return `Error: no such folder "${destRel}".`;
    const loc = locateApp(destAbs);
    if (!loc) return 'Error: no HTML entry found to attach the PWA to — build the web app first (e.g. create_web_app), then call add_pwa.';

    const name = (typeof args.name === 'string' && args.name.trim() ? args.name.trim() : 'My App').replace(/["'<>]/g, '').slice(0, 60);
    const shortName = (typeof args.short_name === 'string' && args.short_name.trim() ? args.short_name.trim() : name).replace(/["'<>]/g, '').slice(0, 30);
    const theme = cleanHex(args.theme_color, '#4f46e5');
    const bg = cleanHex(args.background_color, '#ffffff');
    const fg = readableOn(theme);
    const letter = (name.match(/[A-Za-z0-9]/)?.[0] ?? 'A').toUpperCase();

    const iconsDir = path.join(loc.assetRoot, 'icons');
    fs.mkdirSync(iconsDir, { recursive: true });

    // Always write the vector icon (instant, never missing); add PNG rasters when Chromium is available.
    const svg = iconSvg(letter, theme, fg, 512);
    fs.writeFileSync(path.join(iconsDir, 'icon.svg'), svg);
    let hasPng = false;
    try {
      const png192 = await svgToPng(iconSvg(letter, theme, fg, 192), 192, 192, 1);
      const png512 = await svgToPng(svg, 512, 512, 1);
      if (png192 && png512) {
        fs.writeFileSync(path.join(iconsDir, 'icon-192.png'), png192);
        fs.writeFileSync(path.join(iconsDir, 'icon-512.png'), png512);
        hasPng = true;
      }
    } catch {
      /* fall back to the SVG icon — already written */
    }

    const icons = [
      ...(hasPng
        ? [
            { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
            { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
            { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
          ]
        : []),
      // The vector icon scales to any size and is valid for any+maskable — guarantees a working icon.
      { src: 'icons/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' },
    ];
    const manifest = {
      name,
      short_name: shortName,
      start_url: './',
      scope: './',
      display: 'standalone',
      orientation: 'portrait',
      theme_color: theme,
      background_color: bg,
      icons,
    };
    fs.writeFileSync(path.join(loc.assetRoot, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));
    fs.writeFileSync(path.join(loc.assetRoot, 'sw.js'), SERVICE_WORKER);

    try {
      wireHtml(loc.htmlFile, theme, hasPng);
    } catch (e: any) {
      return `Wrote the manifest/service-worker/icons, but couldn't auto-wire ${path.basename(loc.htmlFile)} (${e?.message ?? e}). Add to its <head>: <link rel="manifest" href="manifest.webmanifest"> + <meta name="theme-color" content="${theme}">, and before </body>: ${REG_SCRIPT}`;
    }

    const where = loc.assetRoot === destAbs ? (destRel === '.' ? 'the workspace root' : `${destRel}/`) : `${path.relative(destAbs, loc.assetRoot) || '.'}/`;
    return (
      `Made it an installable PWA (correct by construction, won't loop the verify gate). In ${where}: ` +
      `manifest.webmanifest (name "${name}", theme ${theme}), sw.js (safe offline SW — network-first pages, ` +
      `cache-first assets, APIs untouched), and icons/ (icon.svg${hasPng ? ' + icon-192/512.png' : ''} — a real ` +
      `branded "${letter}" mark, never missing). Wired into ${path.basename(loc.htmlFile)}: manifest link, ` +
      `theme-color, apple-touch-icon, and the service-worker registration. It installs from the browser ` +
      `("Add to home screen") and works offline. Publish with publish_app — the app also works fully WITHOUT ` +
      `the service worker (progressive enhancement), so verification stays green.`
    );
  },
};
