import fs from 'node:fs';
import path from 'node:path';
import { repoRoot } from '../../config';
import { resolveInWorkspace, type ToolDef } from './common';

const SKELETONS = path.join(repoRoot, 'server', 'assets', 'skeletons');
const SERVICE = path.join(SKELETONS, 'service');
const API_ONLY = path.join(SKELETONS, 'api-only');
const MODULES = path.join(SKELETONS, 'modules');

export interface ModuleMeta {
  name: string;
  label: string;
  deps: string[];
  extraDeps?: Record<string, string>;
  mounts?: Array<{ path: string; router: string; auth?: boolean; org?: boolean }>;
  nav?: Array<{ key: string; label: string; icon: string; page: string }>;
  boot?: string;
  verify?: { routes?: Array<{ method: string; path: string; auth?: boolean; expect: number }>; sse?: string; isolation?: { orgRoute: string } };
}

export function listModules(): string[] {
  try {
    return fs.readdirSync(MODULES).filter((d) => fs.existsSync(path.join(MODULES, d, 'module.json')));
  } catch {
    return [];
  }
}

export function readModule(name: string): ModuleMeta | null {
  try {
    return JSON.parse(fs.readFileSync(path.join(MODULES, name, 'module.json'), 'utf8'));
  } catch {
    return null;
  }
}

/** Resolve requested modules + their declared deps into a deduped install order (pure). */
export function resolveModules(requested: string[]): { order: string[]; unknown: string[] } {
  const unknown: string[] = [];
  const order: string[] = [];
  const seen = new Set<string>();
  const visit = (name: string) => {
    if (seen.has(name)) return;
    seen.add(name);
    const meta = readModule(name);
    if (!meta) {
      unknown.push(name);
      return;
    }
    for (const d of meta.deps || []) visit(d);
    order.push(name);
  };
  for (const m of requested) visit(String(m).trim());
  return { order, unknown };
}

function copyTree(src: string, dest: string) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const f of fs.readdirSync(src)) {
    const s = path.join(src, f);
    const d = path.join(dest, f);
    if (fs.statSync(s).isDirectory()) copyTree(s, d);
    else fs.copyFileSync(s, d);
  }
}

const TEXT_EXT = new Set(['.js', '.jsx', '.json', '.html', '.css', '.md', '.sql', '.txt']);
function patchPlaceholders(dir: string, map: Record<string, string>) {
  for (const f of fs.readdirSync(dir)) {
    const p = path.join(dir, f);
    if (fs.statSync(p).isDirectory()) {
      patchPlaceholders(p, map);
      continue;
    }
    if (!TEXT_EXT.has(path.extname(f))) continue;
    let s = fs.readFileSync(p, 'utf8');
    let changed = false;
    for (const [k, v] of Object.entries(map)) {
      if (s.includes(k)) {
        s = s.split(k).join(v);
        changed = true;
      }
    }
    if (changed) fs.writeFileSync(p, s);
  }
}

const slugify = (s: string) =>
  String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'app';

/** Generate server/api.js from the installed modules' mounts + boot hooks (pure string build). */
export function generateApiJs(mods: ModuleMeta[]): string {
  const imports: string[] = ["import authRouter from './routes/auth.js';", "import { requireAuth } from './middleware/auth.js';"];
  const mounts: string[] = ["  app.use('/api/auth', authRouter);"];
  const boots: string[] = [];
  const needsOrg = mods.some((m) => m.mounts?.some((x) => x.org));
  if (needsOrg) imports.push("import { withOrg } from './middleware/withOrg.js';");
  let i = 0;
  for (const m of mods) {
    for (const mount of m.mounts || []) {
      const v = `r${i++}`;
      imports.push(`import ${v} from '${mount.router}';`);
      const guards = [mount.auth ? 'requireAuth' : '', mount.org ? 'withOrg' : ''].filter(Boolean);
      mounts.push(`  app.use('${mount.path}', ${[...guards, v].join(', ')});`);
    }
    if (m.boot) {
      const v = `boot${i++}`;
      imports.push(`import { startJobs as ${v} } from '${m.boot}';`);
      boots.push(`  ${v}();`);
    }
  }
  return [
    '// GENERATED by scaffold_app — module routers mount here. Regenerate by re-running the tool;',
    '// hand-add new routers following the same guard pattern (requireAuth / withOrg).',
    ...imports,
    '',
    'export function mountApi(app) {',
    ...mounts,
    ...boots,
    '}',
    '',
  ].join('\n');
}

/** Generate client/src/modules.gen.js from the installed modules' nav entries (pure). */
export function generateModulesJs(mods: ModuleMeta[]): string {
  const imports: string[] = ["import Home from './pages/Home.jsx';", "import Account from './pages/Account.jsx';"];
  const pages: string[] = ["  { key: 'home', label: 'Home', icon: 'dashboard', component: Home },"];
  const seen = new Set(['home', 'account']);
  for (const m of mods) {
    for (const nav of m.nav || []) {
      if (seen.has(nav.key)) continue;
      seen.add(nav.key);
      const comp = nav.key.charAt(0).toUpperCase() + nav.key.slice(1).replace(/[^a-zA-Z0-9]/g, '');
      imports.push(`import ${comp} from '${nav.page}';`);
      pages.push(`  { key: '${nav.key}', label: '${nav.label}', icon: '${nav.icon}', component: ${comp} },`);
    }
  }
  // Account (profile + password) is part of the production base — every app with logins gets it.
  pages.push("  { key: 'account', label: 'Account', icon: 'settings', component: Account },");
  return [
    '// GENERATED by scaffold_app — the installed modules’ pages and nav.',
    ...imports,
    '',
    'export const PAGES = [',
    ...pages,
    '];',
    '',
  ].join('\n');
}

/** The verify manifest the quality gate reads — the scaffold DECLARES its own verification. */
export function generateVerifyManifest(slug: string, mods: ModuleMeta[]): object {
  const routes: object[] = [
    { method: 'GET', path: '/api/health', expect: 200 },
    { method: 'GET', path: '/api/auth/me', auth: true, expect: 200 },
  ];
  let sse: string | undefined;
  let isolation: object | undefined;
  for (const m of mods) {
    for (const r of m.verify?.routes || []) routes.push({ ...r, path: r.path.replace('__DEMO_ORG__', 'demo') });
    if (m.verify?.sse) sse = m.verify.sse;
    if (m.verify?.isolation) isolation = { orgRoute: m.verify.isolation.orgRoute.replace('__DEMO_ORG__', 'demo') };
  }
  return {
    demo: { email: `demo@${slug}.app`, password: 'demo1234' },
    routes,
    ...(sse ? { sse } : {}),
    ...(isolation ? { isolation } : {}),
    note: 'Read by the ArksAI quality gate: it signs in with `demo` and walks every page, and asserts each route. Keep this file and the seeded demo user in sync with the app.',
  };
}

function generateContract(name: string, slug: string, mods: ModuleMeta[]): string {
  return `# BUILD CONTRACT — ${name} (generated by scaffold_app; BINDING for every later step/session)

- ONE service: \`npm install && npm run build && npm start\` on PORT (default 4000). API under /api/* registers BEFORE the SPA fallback. Asset paths are RELATIVE (path-proxy safe).
- RESPONSES: flat camelCase JSON. Lists are ARRAYS (not wrapped). Errors are \`{ "error": "human-readable reason" }\` with the right status (400 invalid, 401 unauthenticated, 404 not found/other-tenant).
- AUTH: \`Authorization: Bearer <jwt>\` from POST /api/auth/login|signup. Demo account (NEVER remove — the quality gate uses it): demo@${slug}.app / demo1234.
- DATA: SQLite at data/app.db; migrations in server/migrations/*.sql run once each (idempotent runner); seeds in server/seed/*.js seed ONLY when their data is absent. Never wipe data on seed.
- NEW ENTITIES: clone the exemplar (server/routes/items.js + its migration/seed/page) and rename — keep the same shapes, guards and validation pattern.
- MODULES INSTALLED: ${mods.map((m) => m.name).join(', ') || '(none)'}. Their mounts live in server/api.js; their pages in client/src/modules.gen.js.
- STYLES: mechanics live in app.css (responsive layer stays at the END of the file); the look is tokens.css only.
- PRODUCTION-COMPLETE, NOT A DEMO: the delivered app is the finished product. The Items exemplar MUST be cloned/renamed into the real domain entities (or removed) — never delivered as a literal "Items" page. EXEMPLAR seeds (products/resources) must be replaced with the app's real data. All copy is real product copy (no lorem ipsum / coming soon / placeholder screens); every visible control performs its real action; auth endpoints are rate-limited and the Account page (profile + password) ships working — keep them.
`;
}

export const scaffoldAppTool: ToolDef = {
  name: 'scaffold_app',
  description:
    'Scaffold a COMPLETE full-stack app (Express + SQLite API + React client, ONE service) that is ' +
    'correct by construction: auth with a seeded demo login, idempotent migrations/seeds, the ' +
    '/apps-proxy-safe publish shape, responsive mechanics, and a generated .arksai/CONTRACT.md + ' +
    '.arksai/verify.json the quality gate verifies against. ALWAYS start any app with a backend ' +
    'here (never hand-roll the server shell, auth, or tenancy). Available modules: ' +
    'crud (the exemplar entity you CLONE per real entity), orgs (multi-tenant workspaces + invites ' +
    '+ isolation middleware), dashboard (stats + ring, needs crud), forms (public intake + outbox), ' +
    'uploads (authed files in data/uploads), realtime (SSE live updates), jobs (in-process ' +
    'scheduler), catalog (products + cart + server-priced checkout + order fulfillment — commerce ' +
    'with no payment keys; NEVER hand-roll a cart/checkout), payments (REAL Stripe Checkout + PayPal on '+
    'top of catalog — the owner pastes their keys on the in-app Payments page and online payment goes '+
    'live instantly; server-side verified, no webhooks needed; until keys exist checkout stays the '+
    'order-request flow; NEVER hand-roll a payment integration), booking (resources + per-day slots + ' +
    'conflict-safe reservations in a transaction — NEVER hand-roll slot math), cms-lite (markdown ' +
    'posts + editor + a public read API for blogs/docs). ' +
    'The base is production-grade out of the box: security headers, rate-limited auth, ' +
    'a working Account page (profile + password change), JSON error envelope everywhere. After ' +
    'scaffolding: rename/clone the exemplar into the REAL domain entities, write real copy, theme ' +
    'via tokens.css — the skeleton mechanics (server.js, api.js guards, auth flow, responsive ' +
    'layer) stay intact. The deliverable is the COMPLETE product, never a demo: an untouched ' +
    '"Items" page or scaffold copy left in the delivered app fails the quality gate.',
  parameters: {
    type: 'object',
    properties: {
      name: { type: 'string', description: 'The app name (e.g. "TaskForge").' },
      base: { type: 'string', enum: ['service', 'api-only'], description: 'Skeleton base: "service" (default — API + React client on one port) or "api-only" (a pure JSON API with key auth + a self-documenting index page; no client, no modules — for webhooks/integrations/developer APIs).' },
      modules: { type: 'array', items: { type: 'string' }, description: 'Capability modules to install (deps auto-added).' },
      description: { type: 'string', description: 'One sentence of what the app does (lands on the auth page + home).' },
      tagline: { type: 'string', description: 'Short brand line for the auth art panel.' },
      dest: { type: 'string', description: 'Workspace subfolder (default the workspace root ".").' },
    },
    required: ['name'],
  },
  modes: ['code'],
  summarize: (a) => `scaffold app "${a?.name ?? ''}"${Array.isArray(a?.modules) && a.modules.length ? ` + ${a.modules.join(',')}` : ''}`,
  async run(args, ctx) {
    const name = String(args.name || '').trim();
    if (!name) return 'Error: name is required.';
    const dest = resolveInWorkspace(ctx.repoDir, String(args.dest || '.'));

    // Brownfield guard: never clobber an existing project. (uploads/ and dotfiles don't count.)
    const existing = fs.existsSync(dest)
      ? fs.readdirSync(dest).filter((f) => !f.startsWith('.') && f !== 'uploads' && f !== 'knowledge')
      : [];
    if (existing.includes('package.json') || existing.length > 5) {
      return (
        'Error: the workspace already contains a project — scaffold_app never overwrites existing code. ' +
        'Work with the existing codebase directly (read it first), or scaffold into an empty subfolder via dest.'
      );
    }

    // API-ONLY base: a pure JSON API (key auth + self-documenting index). No client, no modules.
    if (String(args.base || 'service') === 'api-only') {
      if (Array.isArray(args.modules) && args.modules.length) {
        return 'Error: the api-only base takes NO modules (they are client-app capabilities). Re-call without modules, or use base "service".';
      }
      copyTree(API_ONLY, dest);
      const slug0 = slugify(name);
      patchPlaceholders(dest, {
        __APP_SLUG__: slug0,
        __APP_NAME__: name,
        __APP_DESCRIPTION__: String(args.description || `${name} — a JSON API.`),
      });
      const arksDir = path.join(dest, '.arksai');
      fs.mkdirSync(arksDir, { recursive: true });
      fs.writeFileSync(
        path.join(arksDir, 'verify.json'),
        JSON.stringify(
          {
            routes: [
              { method: 'GET', path: '/api/health', expect: 200 },
              { method: 'GET', path: '/', expect: 200 },
              { method: 'GET', path: '/api/records', expect: 401 },
            ],
            note: 'API-only app: the gate asserts these routes (no browser walk needed). Keep this in sync with server/api.js ENDPOINTS.',
          },
          null,
          2,
        ),
      );
      fs.writeFileSync(
        path.join(arksDir, 'CONTRACT.md'),
        `# BUILD CONTRACT — ${name} (api-only; BINDING for every later step/session)\n\n` +
          `- ONE service: \`npm install && npm run seed && npm start\` on PORT (default 4000). JSON only under /api/*; GET / is the self-documenting index (server/docs.js renders server/api.js ENDPOINTS — keep it truthful when adding routes).\n` +
          `- RESPONSES: flat camelCase JSON; errors are \`{ "error": "reason" }\` with the right status. AUTH: X-API-Key (or Bearer) — the first key prints ONCE at seed.\n` +
          `- NEW ENTITIES: clone server/routes/records.js (+ migration) and rename; add the endpoints to ENDPOINTS in server/api.js.\n` +
          `- PRODUCTION-COMPLETE: the exemplar "records" resource MUST be renamed/cloned into the real domain; the docs page lists every real endpoint.\n`,
      );
      return (
        `Scaffolded "${name}" (api-only base).\n` +
        `Boot: npm install && npm run seed && npm start (PORT env, default 4000). The seed prints the first API key ONCE.\n` +
        `GET / serves a self-documenting endpoint index; keep ENDPOINTS in server/api.js truthful as you add routes.\n` +
        `Next: clone server/routes/records.js into the REAL domain resources and update ENDPOINTS + .arksai/verify.json.`
      );
    }

    const { order, unknown } = resolveModules(Array.isArray(args.modules) ? args.modules.map(String) : []);
    if (unknown.length) {
      return `Error: unknown module(s): ${unknown.join(', ')}. Available: ${listModules().join(', ')}. Fix the list and call again.`;
    }
    const mods = order.map((n) => readModule(n)!) as ModuleMeta[];

    // 1 · Base skeleton
    copyTree(SERVICE, dest);
    // 2 · Module overlays (deliberate overrides allowed)
    for (const m of mods) copyTree(path.join(MODULES, m.name, 'files'), dest);
    // 3 · Extra npm deps
    const pkgPath = path.join(dest, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    for (const m of mods) Object.assign(pkg.dependencies, m.extraDeps || {});
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
    // 4 · Generated wiring
    fs.writeFileSync(path.join(dest, 'server', 'api.js'), generateApiJs(mods));
    fs.writeFileSync(path.join(dest, 'client', 'src', 'modules.gen.js'), generateModulesJs(mods));
    // 5 · Placeholders
    const slug = slugify(name);
    patchPlaceholders(dest, {
      __APP_SLUG__: slug,
      __APP_NAME__: name,
      __APP_INITIAL__: name.charAt(0).toUpperCase(),
      __APP_TAGLINE__: String(args.tagline || `${name} — everything in one place.`),
      __APP_DESCRIPTION__: String(args.description || `${name}, scaffolded and ready to build.`),
    });
    // 6 · The gate's manifest + the binding contract
    const arks = path.join(dest, '.arksai');
    fs.mkdirSync(arks, { recursive: true });
    fs.writeFileSync(path.join(arks, 'verify.json'), JSON.stringify(generateVerifyManifest(slug, mods), null, 2));
    fs.writeFileSync(path.join(arks, 'CONTRACT.md'), generateContract(name, slug, mods));

    return (
      `Scaffolded "${name}" (service skeleton${mods.length ? ` + modules: ${mods.map((m) => m.name).join(', ')}` : ''}).\n` +
      `Boot: npm install && npm run seed && npm run build && npm start (PORT env, default 4000).\n` +
      `Demo login (the quality gate signs in with it — NEVER remove): demo@${slug}.app / demo1234.\n` +
      `BINDING conventions are in .arksai/CONTRACT.md; the gate verifies .arksai/verify.json.\n` +
      `Next: clone server/routes/items.js (+ its migration/seed/page) into the REAL domain entities, ` +
      `replace placeholder copy with real content, theme via client/src/styles/tokens.css ONLY. ` +
      `Do not modify server.js, server/api.js guard wiring, the auth flow, the Account page, or the ` +
      `responsive layer's position.\n` +
      `THE BAR IS PRODUCTION-COMPLETE, NOT A DEMO: the gate rejects an app still showing the untouched ` +
      `"Items" exemplar, the scaffold home copy, or any placeholder/coming-soon screen — finish the ` +
      `real product before delivering.`
    );
  },
};
